#!/bin/bash

# Script template generated by https://slurm-jsg.ebi.ac.uk/

#Submit this script with: sbatch thefilename
#For more details about each parameter, please check SLURM sbatch documentation https://slurm.schedmd.com/sbatch.html

#SBATCH --time=24:00:00   # walltime
#SBATCH --ntasks=1   # number of tasks
#SBATCH --cpus-per-task=2   # number of CPUs Per Task i.e if your code is multi-threaded
#SBATCH --nodes=1   # number of nodes
#SBATCH -p production   # partition(s)
#SBATCH --mem=2G   # memory per node
#SBATCH -J "CRITICAL INDEXES"   # job name
#SBATCH --mail-user=prabhat   # email address
#SBATCH --mail-type=BEGIN,END,FAIL

# To launch job:
# $ scp create_critical_indexes.* codon:~
# $ ssh codon
# $ chmod +x create_critical_indexes.sh
# $ sbatch create_critical_indexes.sh

PGPASSWORD=$PV_DBPASS psql -h $PV_DB -p $PV_DBPORT -d $PV_DBNAME -U $PV_DBUSER -f create_critical_indexes.sql