#!/bin/sh
GITLAB_PV_DV_DB_PWD=$(printf ${GITLAB_PV_DV_DB_PWD} | base64)
GITLAB_PV_PB_DB_PWD=$(printf ${GITLAB_PV_PB_DB_PWD} | base64)
GITLAB_PV_FB_DB_PWD=$(printf ${GITLAB_PV_FB_DB_PWD} | base64)
envsubst '${GITLAB_PV_DV_DB_URL} ${GITLAB_PV_DV_DB_USER} ${GITLAB_PV_DV_DB_PWD} ${GITLAB_PV_PB_DB_URL} ${GITLAB_PV_PB_DB_USER} ${GITLAB_PV_PB_DB_PWD} ${GITLAB_PV_FB_DB_URL} ${GITLAB_PV_FB_DB_USER} ${GITLAB_PV_FB_DB_PWD}' <&0